# Generated by Django 3.1.7 on 2021-06-08 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('elements', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MisClicks',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
            ],
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='PinchZoom',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('percentage', models.FloatField(blank=True, null=True)),
            ],
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='Scroll',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('scroll_points', models.TextField()),
                ('scroll_objects', models.TextField()),
            ],
            bases=('events.event',),
        ),
    ]
