# Generated by Django 3.1.7 on 2022-05-25 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event')),
                ('x', models.FloatField(blank=True, null=True)),
                ('y', models.FloatField(blank=True, null=True)),
            ],
            bases=('events.event',),
        ),
        migrations.CreateModel(
            name='Sitio',
            fields=[
                ('nombre', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('corregido', models.BooleanField()),
                ('publications', models.ManyToManyField(to='events.Session')),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('sitio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='events.sitio')),
            ],
        ),
    ]
