# Generated by Django 3.1.7 on 2023-09-30 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='complete',
            field=models.BooleanField(default=True),
        ),
    ]
