# Generated by Django 3.1.7 on 2021-06-07 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField()),
                ('elements', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='misclicks',
            name='elements',
        ),
        migrations.RemoveField(
            model_name='misclicks',
            name='id',
        ),
        migrations.RemoveField(
            model_name='misclicks',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='misclicks',
            name='type',
        ),
        migrations.RemoveField(
            model_name='pinchzoom',
            name='elements',
        ),
        migrations.RemoveField(
            model_name='pinchzoom',
            name='id',
        ),
        migrations.RemoveField(
            model_name='pinchzoom',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='pinchzoom',
            name='type',
        ),
        migrations.RemoveField(
            model_name='scroll',
            name='elements',
        ),
        migrations.RemoveField(
            model_name='scroll',
            name='id',
        ),
        migrations.RemoveField(
            model_name='scroll',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='scroll',
            name='type',
        ),
        migrations.AddField(
            model_name='misclicks',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pinchzoom',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scroll',
            name='event_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.event'),
            preserve_default=False,
        ),
    ]
