# Generated by Django 3.1.7 on 2021-06-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210607_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
