# Generated by Django 3.1.7 on 2023-09-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_session_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='complete_balcon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='session',
            name='complete_ioma',
            field=models.BooleanField(default=True),
        ),
    ]
