# Generated by Django 3.1.7 on 2021-07-10 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210608_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scroll',
            name='scroll_objects',
        ),
        migrations.AlterField(
            model_name='element',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='events.event'),
        ),
    ]
