# Generated by Django 3.1.7 on 2021-07-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210710_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=100, null=True)),
                ('os', models.CharField(max_length=100, null=True)),
                ('tablet', models.CharField(max_length=100, null=True)),
                ('user_agent', models.CharField(max_length=100, null=True)),
                ('build', models.CharField(max_length=100, null=True)),
                ('height', models.FloatField(null=True)),
                ('width', models.FloatField(null=True)),
                ('webkit', models.FloatField(null=True)),
            ],
        ),
    ]
