# Generated by Django 3.1.7 on 2021-07-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='type',
            field=models.CharField(default='device', max_length=50),
            preserve_default=False,
        ),
    ]
