# Generated by Django 3.1.7 on 2021-07-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='mobile',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
