# Generated by Django 3.1.7 on 2021-11-15 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20211113_1125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='session',
        ),
        migrations.RemoveField(
            model_name='event',
            name='session',
        ),
        migrations.DeleteModel(
            name='Session',
        ),
    ]
